////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////
package Test;

import GUI.BadConsequenceView;
import GUI.TreasureView;
import Model.BadConsequence;
import Model.BadConsequenceDeath;
import Model.BadConsequenceNumberTreasures;
import Model.BadConsequenceSpecificTreasures;
import Model.Cultist;
import Model.CultistPlayer;
import Model.Napakalaki;
import Model.Player;
import Model.Treasure;
import Model.TreasureKind;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Juan Luis
 */
public class TestExamenJuanlu extends javax.swing.JFrame {
    
    Treasure t1,t2,t3,t4,t5,t6;
    ArrayList<Treasure> vt, ht;
    BadConsequence b1,b2,b3;
    Player p;
    BadConsequenceView b1View,b2view,b3View;

    /**
     * Creates new form TestExamenJuanlu
     */
    public TestExamenJuanlu() {
        initComponents();
        
        t1 = new Treasure("Juanlu",2000,10,15, TreasureKind.BOTHHANDS);
        t2 = new Treasure("Dropbox MSN",800,8,10,TreasureKind.ONEHAND);
        t3 = new Treasure("Bota de CR7",1200,2,8,TreasureKind.SHOE);
        t4 = new Treasure("La fuerza de Mr. A.",1001,0,0,TreasureKind.NECKLACE);
        t5 = new Treasure("La cabeza de mi hermano",0,3,9,TreasureKind.HELMET);
        t6 = new Treasure("Camiseta de R",400,2,8,TreasureKind.ARMOR);
        
        vt = new ArrayList(Arrays.asList(t1,t2,t4));
        ht = new ArrayList(Arrays.asList(t3,t5,t6));
        
        b1 = new BadConsequenceSpecificTreasures("Pierdes todos tus tesoros de manos visibles y pies ocultos.", 2,
                new ArrayList(Arrays.asList(TreasureKind.ONEHAND,TreasureKind.ONEHAND,TreasureKind.BOTHHANDS)) ,
                        new ArrayList(Arrays.asList(TreasureKind.SHOE)));
        
        b2 = new BadConsequenceNumberTreasures("Los exámenes rebuscados te hacen perder 4 niveles y todos tus tesoros visibles",
                  4, 99,0);
        
        b3 = new BadConsequenceDeath("Suspendes PDOO por los exámenes de 20 minutos. Mueres", true);
        
        // Deletes old information
        visibleTreasuresPanel.removeAll();

        // For each treasure in the list add its view to the panel.
        for (Treasure t : vt) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            visibleTreasuresPanel.add(aTreasureView);
        }

        // Update the panel
        visibleTreasuresPanel.repaint();
        visibleTreasuresPanel.revalidate();
        
                // Deletes old information
        hiddenTreasuresPanel.removeAll();

        // For each treasure in the list add its view to the panel.
        for (Treasure t : ht) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            hiddenTreasuresPanel.add(aTreasureView);
        }

        // Update the panel
        hiddenTreasuresPanel.repaint();
        hiddenTreasuresPanel.revalidate();
        
        b1View = new BadConsequenceView();
        b2view = new BadConsequenceView();
        b3View = new BadConsequenceView();
        b1View.setBadConsequence(b1);
        b2view.setBadConsequence(b2);
        b3View.setBadConsequence(b3);
        b1View.setVisible(true);
        b2view.setVisible(true);
        b3View.setVisible(true);
        badConsPanel.add(b1View);
        badConsPanel.add(b2view);
        badConsPanel.add(b3View);
        
        p = new Player("Suspendedor");
        p.setVisibleTreasureList(new ArrayList(Arrays.asList(new Treasure("Tesoro para no DieIfNoTreasures",100,1,1,TreasureKind.ONEHAND))));
        playerView1.setPlayer(p);
        playerView1.enableButtons(false);
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hiddenTreasuresPanel = new javax.swing.JPanel();
        visibleTreasuresPanel = new javax.swing.JPanel();
        playerView1 = new GUI.PlayerView();
        btAdjust = new javax.swing.JButton();
        btBuy = new javax.swing.JButton();
        btCultist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        badConsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hiddenTreasuresPanel.setBackground(new java.awt.Color(255, 255, 255));
        hiddenTreasuresPanel.setBorder(new javax.swing.border.MatteBorder(null));

        visibleTreasuresPanel.setBackground(new java.awt.Color(255, 255, 255));
        visibleTreasuresPanel.setBorder(new javax.swing.border.MatteBorder(null));

        btAdjust.setText("Adjust");
        btAdjust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdjustActionPerformed(evt);
            }
        });

        btBuy.setText("Buy");
        btBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuyActionPerformed(evt);
            }
        });

        btCultist.setText("Make Cultist");
        btCultist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCultistActionPerformed(evt);
            }
        });

        badConsPanel.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(badConsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hiddenTreasuresPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visibleTreasuresPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btAdjust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCultist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visibleTreasuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdjust)
                                .addGap(10, 10, 10)
                                .addComponent(btBuy)
                                .addGap(9, 9, 9)
                                .addComponent(btCultist)))
                        .addGap(18, 18, 18)
                        .addComponent(hiddenTreasuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdjustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdjustActionPerformed
        b1 = b1.adjustToFitTreasureLists(vt, ht);
        b2 = b2.adjustToFitTreasureLists(vt, ht);
        b3 = b3.adjustToFitTreasureLists(vt, ht);

        b1View.setBadConsequence(b1);
        b2view.setBadConsequence(b2);
        b3View.setBadConsequence(b3);
        this.repaint();
    }//GEN-LAST:event_btAdjustActionPerformed

    private void btBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuyActionPerformed
        p.buyLevels(vt, ht);
        playerView1.setPlayer(p);
        this.repaint();
    }//GEN-LAST:event_btBuyActionPerformed

    private void btCultistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCultistActionPerformed
        Cultist c = new Cultist("JUANLUCTARIO", 5);
        p = new CultistPlayer(p, c);
        playerView1.setPlayer(p);
        this.repaint();
    }//GEN-LAST:event_btCultistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestExamenJuanlu().setVisible(true);
            }
        });
        

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel badConsPanel;
    private javax.swing.JButton btAdjust;
    private javax.swing.JButton btBuy;
    private javax.swing.JButton btCultist;
    private javax.swing.JPanel hiddenTreasuresPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.PlayerView playerView1;
    private javax.swing.JPanel visibleTreasuresPanel;
    // End of variables declaration//GEN-END:variables
}
