////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////
package Test;

import GUI.TreasureView;
import Model.BadConsequence;
import Model.BadConsequenceDeath;
import Model.BadConsequenceNumberTreasures;
import Model.BadConsequenceSpecificTreasures;
import Model.Player;
import Model.Treasure;
import Model.TreasureKind;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Juan Luis
 */
public class TestExamenJuanlu extends javax.swing.JFrame {

    /**
     * Creates new form TestExamenJuanlu
     */
    public TestExamenJuanlu() {
        initComponents();
        
        Treasure t1 = new Treasure("Juanlu",2000,10,15, TreasureKind.BOTHHANDS);
        Treasure t2 = new Treasure("Dropbox MSN",800,8,10,TreasureKind.ONEHAND);
        Treasure t3 = new Treasure("Bota de CR7",1200,2,8,TreasureKind.SHOE);
        Treasure t4 = new Treasure("La fuerza de Mr. A.",1001,0,0,TreasureKind.NECKLACE);
        Treasure t5 = new Treasure("La cabeza de mi hermano",0,3,9,TreasureKind.HELMET);
        Treasure t6 = new Treasure("Camiseta de R",400,2,8,TreasureKind.ARMOR);
        
        ArrayList<Treasure> vt = new ArrayList(Arrays.asList(t1,t2,t4));
        ArrayList<Treasure> ht = new ArrayList(Arrays.asList(t3,t5,t6));
        
        BadConsequence b1 = new BadConsequenceSpecificTreasures("Pierdes todos tus tesoros de manos visibles y pies ocultos.", 2,
                new ArrayList(Arrays.asList(TreasureKind.ONEHAND,TreasureKind.ONEHAND,TreasureKind.BOTHHANDS)) ,
                        new ArrayList(Arrays.asList(TreasureKind.SHOE)));
        
        BadConsequence b2 = new BadConsequenceNumberTreasures("Los exámenes rebuscados te hacen perder 4 niveles y todos tus tesoros visibles",
                  4, 99,0);
        
        BadConsequence b3 = new BadConsequenceDeath("Suspendes PDOO por los exámenes de 20 minutos. Mueres", true);
        
        // Deletes old information
        visibleTreasuresPanel.removeAll();

        // For each treasure in the list add its view to the panel.
        for (Treasure t : vt) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            visibleTreasuresPanel.add(aTreasureView);
        }

        // Update the panel
        visibleTreasuresPanel.repaint();
        visibleTreasuresPanel.revalidate();
        
                // Deletes old information
        hiddenTreasuresPanel.removeAll();

        // For each treasure in the list add its view to the panel.
        for (Treasure t : ht) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            hiddenTreasuresPanel.add(aTreasureView);
        }

        // Update the panel
        hiddenTreasuresPanel.repaint();
        hiddenTreasuresPanel.revalidate();
        
        b1View.setBadConsequence(b1);
        b2view.setBadConsequence(b2);
        b3View.setBadConsequence(b3);
        
        Player p = new Player("Suspendedor");
        playerView1.setPlayer(p);
        
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hiddenTreasuresPanel = new javax.swing.JPanel();
        visibleTreasuresPanel = new javax.swing.JPanel();
        b1View = new GUI.BadConsequenceView();
        b2view = new GUI.BadConsequenceView();
        b3View = new GUI.BadConsequenceView();
        playerView1 = new GUI.PlayerView();
        btAdjust = new javax.swing.JButton();
        btBuy = new javax.swing.JButton();
        btCultist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hiddenTreasuresPanel.setBorder(new javax.swing.border.MatteBorder(null));

        visibleTreasuresPanel.setBorder(new javax.swing.border.MatteBorder(null));

        btAdjust.setText("Adjust");
        btAdjust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdjustActionPerformed(evt);
            }
        });

        btBuy.setText("Buy");

        btCultist.setText("Make Cultist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(hiddenTreasuresPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visibleTreasuresPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btAdjust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBuy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCultist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visibleTreasuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdjust)
                                .addGap(10, 10, 10)
                                .addComponent(btBuy)
                                .addGap(9, 9, 9)
                                .addComponent(btCultist)))
                        .addGap(18, 18, 18)
                        .addComponent(hiddenTreasuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdjustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdjustActionPerformed
        
    }//GEN-LAST:event_btAdjustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestExamenJuanlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestExamenJuanlu().setVisible(true);
            }
        });
        

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView b1View;
    private GUI.BadConsequenceView b2view;
    private GUI.BadConsequenceView b3View;
    private javax.swing.JButton btAdjust;
    private javax.swing.JButton btBuy;
    private javax.swing.JButton btCultist;
    private javax.swing.JPanel hiddenTreasuresPanel;
    private GUI.PlayerView playerView1;
    private javax.swing.JPanel visibleTreasuresPanel;
    // End of variables declaration//GEN-END:variables
}
