////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////
package GUI;

import Model.BadConsequence;
import java.awt.Font;

/**
 *
 * @author Juan Luis
 */
public class BadConsequenceView extends javax.swing.JPanel {
    /**
     * BadConsequence whose view is going to be built
     */
    private BadConsequence badConsequenceModel;
    
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
        deathLab.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTxtnVisible = new javax.swing.JLabel();
        nVisibleLab = new javax.swing.JLabel();
        lTxtnHidden = new javax.swing.JLabel();
        nHiddenLab = new javax.swing.JLabel();
        textLab = new javax.swing.JLabel();
        lTxtLevels = new javax.swing.JLabel();
        levelsLab = new javax.swing.JLabel();
        lTxtSpVisible = new javax.swing.JLabel();
        spVisibleLab = new javax.swing.JLabel();
        lTxtSpHidden = new javax.swing.JLabel();
        spHiddenLab = new javax.swing.JLabel();
        deathLab = new javax.swing.JLabel();

        lTxtnVisible.setText("Número de Tesoros Visibles:");

        nVisibleLab.setText("0");

        lTxtnHidden.setText("Número de Tesoros Ocultos:");

        nHiddenLab.setText("0");

        textLab.setText("MAL ROLLO:");

        lTxtLevels.setText("Niveles:");

        levelsLab.setText("0");

        lTxtSpVisible.setText("Tesoros Visibles específicos:");

        spVisibleLab.setText("Ninguno");

        lTxtSpHidden.setText("Tesoros Ocultos específicos:");

        spHiddenLab.setText("Ninguno");

        deathLab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deathLab.setForeground(new java.awt.Color(255, 0, 0));
        deathLab.setText("CAUSA LA MUERTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(spVisibleLab))
                                    .addComponent(lTxtSpVisible)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lTxtSpHidden, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(spHiddenLab))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lTxtLevels)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(levelsLab))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lTxtnHidden)
                                        .addGap(18, 18, 18)
                                        .addComponent(nHiddenLab))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lTxtnVisible)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nVisibleLab))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(deathLab)))
                        .addGap(0, 156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLab, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deathLab)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTxtLevels)
                    .addComponent(levelsLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTxtnVisible)
                    .addComponent(nVisibleLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTxtnHidden)
                    .addComponent(nHiddenLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTxtSpVisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spVisibleLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTxtSpHidden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spHiddenLab)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deathLab;
    private javax.swing.JLabel lTxtLevels;
    private javax.swing.JLabel lTxtSpHidden;
    private javax.swing.JLabel lTxtSpVisible;
    private javax.swing.JLabel lTxtnHidden;
    private javax.swing.JLabel lTxtnVisible;
    private javax.swing.JLabel levelsLab;
    private javax.swing.JLabel nHiddenLab;
    private javax.swing.JLabel nVisibleLab;
    private javax.swing.JLabel spHiddenLab;
    private javax.swing.JLabel spVisibleLab;
    private javax.swing.JLabel textLab;
    // End of variables declaration//GEN-END:variables

    public void setBadConsequence(BadConsequence bc){
        badConsequenceModel = bc;
        this.textLab.setText("MAL ROLLO: " + badConsequenceModel.getText());
        this.levelsLab.setText(Integer.toString(badConsequenceModel.getLevels()));
        
        if(badConsequenceModel instanceof Model.BadConsequenceDeath){
            deathLab.setVisible(true);
        }
        else if(badConsequenceModel instanceof Model.BadConsequenceNumberTreasures){
            this.nVisibleLab.setText(Integer.toString(((Model.BadConsequenceNumberTreasures)badConsequenceModel).getNVisibleTreasures()));
            this.nHiddenLab.setText(Integer.toString(((Model.BadConsequenceNumberTreasures)badConsequenceModel).getNHiddenTreasures()));
            
            if(!badConsequenceModel.isEmpty()){
                this.lTxtnVisible.setFont(lTxtnVisible.getFont().deriveFont(lTxtnVisible.getFont().getStyle() | Font.BOLD));
                this.lTxtnHidden.setFont(lTxtnHidden.getFont().deriveFont(lTxtnHidden.getFont().getStyle() | Font.BOLD));
            }
        }
        
        else if(badConsequenceModel instanceof Model.BadConsequenceSpecificTreasures){
            this.spVisibleLab.setText(((Model.BadConsequenceSpecificTreasures)badConsequenceModel).getSpecificVisibleTreasures().toString());
            this.spHiddenLab.setText(((Model.BadConsequenceSpecificTreasures)badConsequenceModel).getSpecificHiddenTreasures().toString());
            
            if(!badConsequenceModel.isEmpty()){
                this.lTxtSpVisible.setFont(lTxtSpVisible.getFont().deriveFont(lTxtSpVisible.getFont().getStyle() | Font.BOLD));
                this.lTxtSpHidden.setFont(lTxtSpHidden.getFont().deriveFont(lTxtSpHidden.getFont().getStyle() | Font.BOLD));
            }
        }
        repaint();
    }
}
