////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////
package GUI;

import Model.BadConsequence;
import Model.TreasureKind;
import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author Juan Luis
 */
public class BadConsequenceView extends javax.swing.JPanel {
       //------------------- ATTRIBUTES -------------------//
 
    /**
     * BadConsequence whose view is going to be built
     */
    private BadConsequence badConsequenceModel;
    
    //------------------- PRIVATE METHODS -------------------//

    /**
     * Set the components visibility.
     * @param deathLabel
     * @param lTxtSpVisible
     * @param splTxtSpHidden
     * @param spVisibleLab
     * @param spHiddenLab
     * @param nVisibleLab
     * @param nHiddenLab
     * @param levelsLabel 
     */
    private void setComponentsVisibility(boolean deathLabel, boolean levelsLabel,
            boolean nVisibleLab, boolean nHiddenLab, boolean lTxtSpVisible, 
            boolean lTxtSpHidden, boolean spVisibleLab, boolean spHiddenLab){
        this.deathLab.setVisible(deathLabel);
        this.levelsLabel.setVisible(levelsLabel);        
        this.nVisibleLab.setVisible(nVisibleLab);
        this.nHiddenLab.setVisible(nHiddenLab);
        this.lTxtSpVisible.setVisible(lTxtSpVisible);
        this.lTxtSpHidden.setVisible(lTxtSpHidden);
        this.spVisibleLab.setVisible(spVisibleLab);
        this.spHiddenLab.setVisible(spHiddenLab);
    }

    //------------------- CONSTRUCTOR -------------------//
 
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
        deathLab.setVisible(false);
    }

    //------------------- PUBLIC METHODS -------------------//

    /**
     * Sets the bad consequence model represented by the view.
     * @param bc BadConsequence to represent.
     */
    public void setBadConsequence(BadConsequence bc){
        badConsequenceModel = bc;

        // Visualize general information
        this.textLabel.setText("<html>" + badConsequenceModel.getText() + "<html>");
        this.levelsLabel.setText("Levels Lost: " + 
                Integer.toString(badConsequenceModel.getLevels()));
        
        // Modify the bad consequence view according to the type of bad cosnequence.
        if(badConsequenceModel instanceof Model.BadConsequenceDeath){
            this.setComponentsVisibility(true, false, false, false, false, false, false, false);
        }
        else if(badConsequenceModel instanceof Model.BadConsequenceNumberTreasures){
            this.nVisibleLab.setText("Visible Treasures Number: " + 
                    Integer.toString(((Model.BadConsequenceNumberTreasures)badConsequenceModel).getNVisibleTreasures()));
            this.nHiddenLab.setText("Hidden Treasures Number: " +
                    Integer.toString(((Model.BadConsequenceNumberTreasures)badConsequenceModel).getNHiddenTreasures()));
            this.setComponentsVisibility(false, true, true, true, false, false, false, false);
        }        
        else if(badConsequenceModel instanceof Model.BadConsequenceSpecificTreasures){
            ArrayList<TreasureKind> vTreasures = ((Model.BadConsequenceSpecificTreasures)badConsequenceModel).getSpecificVisibleTreasures();
            ArrayList<TreasureKind> hTreasures = ((Model.BadConsequenceSpecificTreasures)badConsequenceModel).getSpecificHiddenTreasures();
            this.spVisibleLab.setText(vTreasures.isEmpty()? "None" : vTreasures.toString());            
            this.spHiddenLab.setText(hTreasures.isEmpty()? "None" : hTreasures.toString());
            this.setComponentsVisibility(false, true, false, false, true, true, true, true);
        }
        setPreferredSize(getPreferredSize());
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTxtSpVisible = new javax.swing.JLabel();
        spVisibleLab = new javax.swing.JLabel();
        lTxtSpHidden = new javax.swing.JLabel();
        spHiddenLab = new javax.swing.JLabel();
        deathLab = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        nVisibleLab = new javax.swing.JLabel();
        nHiddenLab = new javax.swing.JLabel();
        tittleLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();

        lTxtSpVisible.setText("Specific Visible Treasures:");

        spVisibleLab.setText("None");

        lTxtSpHidden.setText("Specific Hidden Treasures:");

        spHiddenLab.setText("None");

        deathLab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deathLab.setForeground(new java.awt.Color(255, 0, 0));
        deathLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deathLab.setText("You Are Dead");

        textLabel.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLabel.setText("You will fail the exam.");

        nVisibleLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nVisibleLab.setText("Visible Treasures Number: 0");

        nHiddenLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nHiddenLab.setText("Hidden Treasures Number: 0");

        tittleLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("Bad Consequence");

        levelsLabel.setText("Levels: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nHiddenLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lTxtSpVisible)
                            .addComponent(levelsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nVisibleLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lTxtSpHidden)
                            .addComponent(spHiddenLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spVisibleLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deathLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deathLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nVisibleLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nHiddenLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTxtSpVisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spVisibleLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTxtSpHidden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spHiddenLab)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deathLab;
    private javax.swing.JLabel lTxtSpHidden;
    private javax.swing.JLabel lTxtSpVisible;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JLabel nHiddenLab;
    private javax.swing.JLabel nVisibleLab;
    private javax.swing.JLabel spHiddenLab;
    private javax.swing.JLabel spVisibleLab;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables

}