////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////
package GUI;

import Model.Cultist;

/**
 *
 * @author Juan Luis
 */
public class CultistView extends javax.swing.JPanel {
    /**
     * Cultist card.
     */
    Cultist cultistModel;
    
    /**
     * Creates new form CultistView
     */
    public CultistView() {
        initComponents();
    }

    /**
     * Sets CultistView
     * @param c Cultist card.
     */
    public void setCultist(Cultist c){
        cultistModel = c;
        txtCultistLabel.setText("<html>" + c.getName() + "<html>");
        gainedLevelsLabel.setText("Gained Levels: +" + Integer.toString(c.getBonus()));
        
        // Repaint the view
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gainedLevelsLabel = new javax.swing.JLabel();
        txtCultistLabel = new javax.swing.JLabel();

        gainedLevelsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gainedLevelsLabel.setForeground(new java.awt.Color(204, 0, 153));
        gainedLevelsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gainedLevelsLabel.setText("Gained Levels: +1");

        txtCultistLabel.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        txtCultistLabel.setForeground(new java.awt.Color(102, 0, 102));
        txtCultistLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCultistLabel.setText("SECTARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCultistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(gainedLevelsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCultistLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gainedLevelsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gainedLevelsLabel;
    private javax.swing.JLabel txtCultistLabel;
    // End of variables declaration//GEN-END:variables
}
