////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////

package GUI;

import Model.Monster;

/**
 * View for a monster in Napakalaki game.
 * @author andreshp, jlsuarez
 */
public class MonsterView extends javax.swing.JPanel {
    
    //------------------- ATTRIBUTES -------------------//

    /**
     * BadConsequence whose view is going to be built
     */
    private Monster monsterModel;
    
    //------------------- CONSTRUCTOR -------------------//

    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    //------------------- SET METHODS -------------------//

    /**
     * Set the monster that the view represents.
     * Actualizes each element in the view.
     * @param m Monster
     */
    public void setMonster(Monster m){
        monsterModel = m;
        this.nameLabel.setText("Monster: " + monsterModel.getName());
        this.levelLabel.setText("Levels: " + Integer.toString(monsterModel.getCombatLevel()));
        this.levelChangeCultistLabel.setText("Levels Against Cultist Player: " + 
                Integer.toString(monsterModel.getSpecialValue()));
        this.badConsequenceView.setBadConsequence(monsterModel.getBadConsequence());
        this.prizeView.setPrize(monsterModel.getPrize());
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        levelChangeCultistLabel = new javax.swing.JLabel();
        prizeView = new GUI.PrizeView();
        badConsequenceView = new GUI.BadConsequenceView();

        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        nameLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Monster: Teacher");

        levelLabel.setText("Level: 0");

        levelChangeCultistLabel.setText("Level Against Cultist Player: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(levelChangeCultistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelChangeCultistLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView;
    private javax.swing.JLabel levelChangeCultistLabel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel nameLabel;
    private GUI.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables
}
