////////////////////////////////////////////////////////////////////////////////
// Authors: Juan Luis Suárez Díaz, Andrés Herrera Poyatos
// Universidad de Granada, March, 2015
// Programación Orientada a Objetos - Napakalaki
////////////////////////////////////////////////////////////////////////////////

package GUI;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Class with a view to obtain players name at the 
 * begining of Napakalaki game.
 * @author andreshp, jlsuarez
 */
public class PlayerNamesCapture extends javax.swing.JDialog {

    //------------------ ATTRIBUTES ------------------//

    ArrayList<String> names;

    //-------------------- PRIVATE --------------------//

    /**
     * Fills the panels with new labels and text fields.
     * There is one label and text field per player.
     * @param numPlayers Number of players in the game.
     */
    public void fillPanels(int numPlayers) {
        // Deletes old information
        playersPanel.removeAll();
        namesPanel.removeAll();
        Dimension dim;


        // Adds n players 
        for (int i = 0; i < numPlayers; i++) {
            dim = new Dimension(70,22);
            JLabel player = new JLabel();
            player.setText("Player " + Integer.toString(i+1) + ": ");
            player.setSize(dim);
            player.setMinimumSize(dim);
            player.setMaximumSize(dim);
            player.setPreferredSize(dim);
            player.setVisible (true);
            playersPanel.add(player);            
            dim = new Dimension(100,22);
            JTextField name = new JTextField();
            name.setText("Name...");
            name.setSize(dim);
            name.setMinimumSize(dim);
            name.setMaximumSize(dim);
            name.setPreferredSize(dim);
            name.setVisible(true);
            namesPanel.add(name);
        }

        // Update the panels
        playersPanel.repaint();
        playersPanel.revalidate();
        namesPanel.repaint();
        namesPanel.revalidate();
        this.repaint();
        this.revalidate();
    }

    //------------------ CONSTRUCTOR ------------------//

    public PlayerNamesCapture(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener (new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e) {
                System.exit(0);
            }
        });
        
        names = new ArrayList();
    }

    //----------------- GET & SET METHODS -----------------//

    public ArrayList<String> getNames() {
        this.fillPanels((int) nPlayersSpinner.getValue());
        this.setVisible(true);
        return names;
    }

    //----------------- OTHER METHODS -----------------//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        nPlayersLabel = new javax.swing.JLabel();
        nPlayersSpinner = new javax.swing.JSpinner();
        playersPanel = new javax.swing.JPanel();
        namesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Napakalaki");

        play.setBackground(java.awt.Color.blue);
        play.setForeground(java.awt.Color.white);
        play.setText("Play");
        play.setFocusPainted(false);
        play.setName("ButtonPlay"); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        cancel.setBackground(java.awt.Color.red);
        cancel.setForeground(java.awt.Color.white);
        cancel.setText("Cancel");
        cancel.setName("ButtonCancel"); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        nPlayersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nPlayersLabel.setText("Number of Players: ");

        nPlayersSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 1, 6, 1));
        nPlayersSpinner.setAlignmentX(1.0F);
        nPlayersSpinner.setAlignmentY(1.0F);
        nPlayersSpinner.setValue(3);
        nPlayersSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nPlayersSpinnerStateChanged(evt);
            }
        });
        nPlayersSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nPlayersSpinnerKeyTyped(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(1 - 6)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nPlayersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nPlayersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(play)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel)
                        .addGap(20, 20, 20)
                        .addComponent(nPlayersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(nPlayersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(playersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        for (Component text : namesPanel.getComponents()){
            names.add( ((JTextField)text).getText());
        }
        this.dispose(); // Return the control to the user
    }//GEN-LAST:event_playActionPerformed

    private void nPlayersSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nPlayersSpinnerStateChanged
        this.fillPanels((int) nPlayersSpinner.getValue());
    }//GEN-LAST:event_nPlayersSpinnerStateChanged

    private void nPlayersSpinnerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nPlayersSpinnerKeyTyped
        this.fillPanels((int) nPlayersSpinner.getValue());
    }//GEN-LAST:event_nPlayersSpinnerKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nPlayersLabel;
    private javax.swing.JSpinner nPlayersSpinner;
    private javax.swing.JPanel namesPanel;
    private javax.swing.JButton play;
    private javax.swing.JPanel playersPanel;
    // End of variables declaration//GEN-END:variables
}
